package io.sprig.rule;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.fail;

import io.sprig.rule.rules.BuiltInRules;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * Every property key a rule matches must be a property Spring Boot actually reads.
 *
 * <p>sprig shipped two rules whose keys ({@code spring.web.cors.*}, {@code spring.security.debug})
 * exist nowhere in Spring. Spring ignores unknown properties silently, so nothing at runtime says
 * otherwise, and the rules' own fixtures encoded the same invented keys — the suite was green while
 * the rules could not fire on a real project. This test closes that gap by checking rule keys
 * against Spring Boot's own configuration metadata rather than against sprig's fixtures.
 *
 * <p><strong>What absence proves.</strong> The metadata is authoritative in one direction only. A
 * declared key is a real property. An undeclared key is <em>unconfirmed</em>, not disproved: Boot
 * binds properties it never declares, {@code management.endpoint.<id>.access} among them. A failure
 * here is a prompt to check the key against the Boot source or a running app before shipping it,
 * not a verdict that the key is invented.
 *
 * <p>That is what happened with the two rules above. Metadata absence is what pointed at them.
 * Runtime observation, and a search of the jars for a binding that turned out not to exist, are
 * what condemned them.
 *
 * <p>The index is generated by {@code tools/generate-spring-property-index.py}.
 */
class ConfigKeyMetadataTest {

    private static final String INDEX = "/spring-metadata/spring-property-index.txt";

    /** Every property name Spring Boot declares across the indexed releases. */
    private static final Set<String> DECLARED = new LinkedHashSet<>();

    /** Names declared as {@code java.util.Map}, under which any sub-key is a valid property. */
    private static final Set<String> MAP_PREFIXES = new LinkedHashSet<>();

    /**
     * Properties that must be present for the index to be worth trusting. Without this guard a
     * truncated or mis-parsed index would make every assertion below pass vacuously.
     */
    private static final List<String> SENTINELS =
            List.of(
                    "server.port",
                    "server.servlet.session.cookie.http-only",
                    "management.endpoints.web.exposure.include",
                    "management.endpoints.web.cors.allowed-origins",
                    "logging.level");

    /**
     * Rules that read configuration but match on the shape of a key rather than on a fixed list, so
     * they have no keys to declare. Additions here need a reason: the alternative is that a rule
     * quietly opts out of validation.
     */
    private static final Map<String, String> NO_FIXED_KEYS =
            Map.of("SPR-CONFIG-002", "matches any key containing a credential-like segment");

    /**
     * Keys sprig matches on purpose even though Spring's own metadata omits them. Empty is the
     * healthy state; an entry is a deliberate, explained decision, not a place to silence a
     * failure.
     *
     * <p>An entry needs evidence that Boot binds the property, and the reason string is where that
     * evidence goes: either a runtime observation naming the Boot version and the behaviour that
     * changed when the property was set, or a pointer to the class that binds it. "The docs mention
     * it" and "it looks right next to the declared ones" do not clear that bar. Without evidence in
     * the reason, this map mutes the test instead of recording what was checked.
     */
    private static final Map<String, String> ACCEPTED_ABSENCES =
            Map.of(
                    "management.endpoint.shutdown.access",
                            "Boot 3.5.16, exposure.include=health,info,shutdown: POST"
                                    + " /actuator/shutdown answers 404, and 200 with the process"
                                    + " exiting once this is set to unrestricted. Bound"
                                    + " reflectively per endpoint id, so no endpoint declares it.",
                    "management.endpoint.shutdown.enabled",
                            "Boot 2.3.12 and 3.3.13, same exposure: POST /actuator/shutdown answers"
                                    + " 404, and 200 once this is true. Still honoured on 3.5.16.",
                    "management.endpoint.heapdump.access",
                            "Boot 3.5.16, exposure.include=health,info,heapdump: GET"
                                    + " /actuator/heapdump answers 404, and 200 with a JAVA PROFILE"
                                    + " 1.0.2 header once this is read-only or unrestricted.",
                    "management.endpoint.heapdump.enabled",
                            "Boot 3.5.16, exposure.include=*: GET /actuator/heapdump answers 404,"
                                    + " and 200 with a JAVA PROFILE 1.0.2 header once this is true."
                                    + " On 3.3.13 setting it false takes the same request from 200"
                                    + " to 404.");

    @BeforeAll
    static void loadIndex() throws IOException {
        try (InputStream in = ConfigKeyMetadataTest.class.getResourceAsStream(INDEX)) {
            if (in == null) {
                fail(
                        INDEX
                                + " is missing. Regenerate it with"
                                + " tools/generate-spring-property-index.py.");
            }
            try (BufferedReader reader =
                    new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    String name = line.trim();
                    if (name.isEmpty() || name.startsWith("#")) {
                        continue;
                    }
                    if (name.endsWith("*")) {
                        name = name.substring(0, name.length() - 1);
                        MAP_PREFIXES.add(name);
                    }
                    DECLARED.add(name);
                }
            }
        }
    }

    @Test
    @DisplayName("the property index loaded and looks like real Spring metadata")
    void indexIsTrustworthy() {
        assertThat(DECLARED)
                .as("properties parsed from " + INDEX)
                .hasSizeGreaterThan(2000)
                .containsAll(SENTINELS);
        assertThat(MAP_PREFIXES).as("Map-typed properties").contains("logging.level");
    }

    @Test
    @DisplayName("a key Spring does not declare is not accepted by the matcher")
    void matcherRejectsInventedKeys() {
        assertThat(isDeclared("sprig.invented.property")).isFalse();
        assertThat(isDeclared("logging.levelx.org.example")).isFalse();
        assertThat(isDeclared("server.port")).isTrue();
        // A Map-typed property accepts arbitrary sub-keys, which is what makes
        // logging.level.<logger> a real property even though only logging.level is declared.
        assertThat(isDeclared("logging.level.org.springframework.security")).isTrue();
    }

    @Test
    @DisplayName("every configuration-reading rule declares the keys it matches")
    void configRulesDeclareTheirKeys() {
        List<String> undeclared = new ArrayList<>();
        for (Rule rule : BuiltInRules.all()) {
            if (rule.kind() == RuleKind.SOURCE || NO_FIXED_KEYS.containsKey(rule.id())) {
                continue;
            }
            if (rule.configKeys().isEmpty()) {
                undeclared.add(rule.id() + " (" + rule.name() + ")");
            }
        }
        assertThat(undeclared)
                .as(
                        "rules that read configuration but declare no keys, so nothing validates"
                                + " them. Implement configKeys(), or add the rule to NO_FIXED_KEYS with"
                                + " a reason.")
                .isEmpty();
    }

    @Test
    @DisplayName("every declared rule key is confirmed by Spring Boot's metadata, or explained")
    void everyRuleKeyExistsInSpring() {
        Set<String> offenders = new TreeSet<>();
        for (Rule rule : BuiltInRules.all()) {
            for (String key : rule.configKeys()) {
                if (!isDeclared(key) && !ACCEPTED_ABSENCES.containsKey(key)) {
                    offenders.add(rule.id() + " -> " + key);
                }
            }
        }
        assertThat(offenders)
                .as(
                        "rule keys absent from Spring Boot's configuration metadata. Absence is not"
                                + " proof the key is wrong: Boot binds some properties it never"
                                + " declares. It does mean the key is unconfirmed, and Spring ignores"
                                + " unknown properties silently, so an invented key fires on nothing"
                                + " while every fixture stays green. Confirm this one against the Boot"
                                + " source or a running app. Then either repoint the rule at the real"
                                + " property, or add the key to ACCEPTED_ABSENCES with that evidence"
                                + " as its reason.")
                .isEmpty();
    }

    private static boolean isDeclared(String key) {
        if (DECLARED.contains(key)) {
            return true;
        }
        for (String prefix : MAP_PREFIXES) {
            if (key.startsWith(prefix + ".")) {
                return true;
            }
        }
        return false;
    }
}
