package io.sprig.rule;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.fail;

import io.sprig.rule.rules.BuiltInRules;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * Every property key a rule matches must be a property Spring Boot actually reads.
 *
 * <p>sprig shipped two rules whose keys ({@code spring.web.cors.*}, {@code spring.security.debug})
 * exist nowhere in Spring. Spring ignores unknown properties silently, so nothing at runtime says
 * otherwise, and the rules' own fixtures encoded the same invented keys — the suite was green while
 * the rules could not fire on a real project. This test closes that gap by checking rule keys
 * against Spring Boot's own configuration metadata rather than against sprig's fixtures.
 *
 * <p>The index is generated by {@code tools/generate-spring-property-index.py}.
 */
class ConfigKeyMetadataTest {

    private static final String INDEX = "/spring-metadata/spring-property-index.txt";

    /** Every property name Spring Boot declares across the indexed releases. */
    private static final Set<String> DECLARED = new LinkedHashSet<>();

    /** Names declared as {@code java.util.Map}, under which any sub-key is a valid property. */
    private static final Set<String> MAP_PREFIXES = new LinkedHashSet<>();

    /**
     * Properties that must be present for the index to be worth trusting. Without this guard a
     * truncated or mis-parsed index would make every assertion below pass vacuously.
     */
    private static final List<String> SENTINELS =
            List.of(
                    "server.port",
                    "server.servlet.session.cookie.http-only",
                    "management.endpoints.web.exposure.include",
                    "management.endpoints.web.cors.allowed-origins",
                    "logging.level");

    /**
     * Rules that read configuration but match on the shape of a key rather than on a fixed list, so
     * they have no keys to declare. Additions here need a reason: the alternative is that a rule
     * quietly opts out of validation.
     */
    private static final Map<String, String> NO_FIXED_KEYS =
            Map.of("SPR-CONFIG-002", "matches any key containing a credential-like segment");

    /**
     * Keys sprig matches on purpose even though Spring's own metadata omits them. Empty is the
     * healthy state; an entry is a deliberate, explained decision, not a place to silence a
     * failure.
     */
    private static final Map<String, String> ACCEPTED_ABSENCES = Map.of();

    @BeforeAll
    static void loadIndex() throws IOException {
        try (InputStream in = ConfigKeyMetadataTest.class.getResourceAsStream(INDEX)) {
            if (in == null) {
                fail(
                        INDEX
                                + " is missing. Regenerate it with"
                                + " tools/generate-spring-property-index.py.");
            }
            try (BufferedReader reader =
                    new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    String name = line.trim();
                    if (name.isEmpty() || name.startsWith("#")) {
                        continue;
                    }
                    if (name.endsWith("*")) {
                        name = name.substring(0, name.length() - 1);
                        MAP_PREFIXES.add(name);
                    }
                    DECLARED.add(name);
                }
            }
        }
    }

    @Test
    @DisplayName("the property index loaded and looks like real Spring metadata")
    void indexIsTrustworthy() {
        assertThat(DECLARED)
                .as("properties parsed from " + INDEX)
                .hasSizeGreaterThan(2000)
                .containsAll(SENTINELS);
        assertThat(MAP_PREFIXES).as("Map-typed properties").contains("logging.level");
    }

    @Test
    @DisplayName("a key Spring does not declare is not accepted by the matcher")
    void matcherRejectsInventedKeys() {
        assertThat(isDeclared("sprig.invented.property")).isFalse();
        assertThat(isDeclared("logging.levelx.org.example")).isFalse();
        assertThat(isDeclared("server.port")).isTrue();
        // A Map-typed property accepts arbitrary sub-keys, which is what makes
        // logging.level.<logger> a real property even though only logging.level is declared.
        assertThat(isDeclared("logging.level.org.springframework.security")).isTrue();
    }

    @Test
    @DisplayName("every configuration-reading rule declares the keys it matches")
    void configRulesDeclareTheirKeys() {
        List<String> undeclared = new ArrayList<>();
        for (Rule rule : BuiltInRules.all()) {
            if (rule.kind() == RuleKind.SOURCE || NO_FIXED_KEYS.containsKey(rule.id())) {
                continue;
            }
            if (rule.configKeys().isEmpty()) {
                undeclared.add(rule.id() + " (" + rule.name() + ")");
            }
        }
        assertThat(undeclared)
                .as(
                        "rules that read configuration but declare no keys, so nothing validates"
                                + " them. Implement configKeys(), or add the rule to NO_FIXED_KEYS with"
                                + " a reason.")
                .isEmpty();
    }

    @Test
    @DisplayName("every declared rule key is a property Spring Boot actually reads")
    void everyRuleKeyExistsInSpring() {
        Set<String> offenders = new TreeSet<>();
        for (Rule rule : BuiltInRules.all()) {
            for (String key : rule.configKeys()) {
                if (!isDeclared(key) && !ACCEPTED_ABSENCES.containsKey(key)) {
                    offenders.add(rule.id() + " -> " + key);
                }
            }
        }
        assertThat(offenders)
                .as(
                        "rule keys absent from Spring Boot's configuration metadata. Spring ignores"
                                + " unknown properties silently, so these rules cannot fire on a real"
                                + " project and any finding they produce is wrong. Repoint the rule at"
                                + " the real property, or add the key to ACCEPTED_ABSENCES with a"
                                + " reason.")
                .isEmpty();
    }

    private static boolean isDeclared(String key) {
        if (DECLARED.contains(key)) {
            return true;
        }
        for (String prefix : MAP_PREFIXES) {
            if (key.startsWith(prefix + ".")) {
                return true;
            }
        }
        return false;
    }
}
