#!/usr/bin/env python3
"""Regenerate src/test/resources/spring-metadata/spring-property-index.txt.

The index is the union of every property name Spring Boot declares in its own
``META-INF/spring-configuration-metadata.json`` across the Boot 2 and Boot 3
releases listed in VERSIONS. ConfigKeyMetadataTest checks every rule property
key against it, so a rule can no longer ship a key that Spring does not read.

Run from the repository root:

    python3 tools/generate-spring-property-index.py

Requires network access to Maven Central. Jars are cached under
``target/spring-metadata-jars/`` so repeat runs are cheap.
"""

import json
import pathlib
import sys
import urllib.request
import zipfile

# Boot 2 and Boot 3, the range README advertises. One release per minor line;
# patch releases do not add properties, so the newest patch of each line is
# enough. spring-boot-actuator-autoconfigure does not exist as a separate
# artifact before 2.0, which is why 1.5 is absent.
VERSIONS = [
    "2.0.9.RELEASE",
    "2.1.18.RELEASE",
    "2.2.13.RELEASE",
    "2.3.12.RELEASE",
    "2.4.13",
    "2.5.15",
    "2.6.15",
    "2.7.18",
    "3.0.13",
    "3.2.12",
    "3.5.16",
]

ARTIFACTS = [
    "spring-boot",
    "spring-boot-autoconfigure",
    "spring-boot-actuator-autoconfigure",
]

BASE = "https://repo1.maven.org/maven2/org/springframework/boot"

# Properties whose absence would mean the download or the parse silently
# produced a useless index. Every one of these is a property Spring has
# declared for the whole 2.x/3.x range. If any is missing, the index is not
# trustworthy and generation aborts rather than writing a file that would make
# the test pass vacuously.
SENTINELS = [
    "server.port",
    "server.servlet.session.cookie.http-only",
    "server.servlet.session.cookie.secure",
    "management.endpoints.web.exposure.include",
    "management.endpoints.web.cors.allowed-origins",
    "spring.security.user.name",
    "logging.level",
]

ROOT = pathlib.Path(__file__).resolve().parent.parent
CACHE = ROOT / "target" / "spring-metadata-jars"
OUT = ROOT / "src" / "test" / "resources" / "spring-metadata" / "spring-property-index.txt"


def fetch(artifact, version):
    jar = CACHE / f"{artifact}-{version}.jar"
    if jar.exists() and jar.stat().st_size > 0:
        return jar
    url = f"{BASE}/{artifact}/{version}/{artifact}-{version}.jar"
    CACHE.mkdir(parents=True, exist_ok=True)
    print(f"  downloading {artifact} {version}")
    urllib.request.urlretrieve(url, jar)
    if jar.stat().st_size == 0:
        sys.exit(f"ABORT: {url} produced an empty file")
    return jar


def read_metadata(jar):
    """Yield (name, is_map) for every property declared in the jar."""
    with zipfile.ZipFile(jar) as z:
        entries = [n for n in z.namelist() if n.endswith("spring-configuration-metadata.json")]
        if not entries:
            sys.exit(f"ABORT: no configuration metadata inside {jar.name}")
        for entry in entries:
            doc = json.loads(z.read(entry).decode("utf-8"))
            for prop in doc.get("properties", []):
                name = prop.get("name")
                if not name:
                    continue
                # A Map-typed property is a prefix: the user appends arbitrary
                # keys under it, so logging.level.org.springframework.security
                # is valid even though only logging.level is declared.
                yield name, prop.get("type", "").startswith("java.util.Map")


def main():
    names = {}
    for version in VERSIONS:
        print(f"{version}:")
        for artifact in ARTIFACTS:
            for name, is_map in read_metadata(fetch(artifact, version)):
                # A property declared as a map anywhere stays a map: the marker
                # is the union of what every release says about that name.
                names[name] = names.get(name, False) or is_map

    missing = [s for s in SENTINELS if s not in names]
    if missing:
        sys.exit(f"ABORT: sentinel properties missing from the index: {missing}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w") as f:
        f.write("# Generated by tools/generate-spring-property-index.py. Do not edit by hand.\n")
        f.write("# Union of Spring Boot's own configuration metadata across:\n")
        f.write(f"#   {', '.join(VERSIONS)}\n")
        f.write(f"#   artifacts: {', '.join(ARTIFACTS)}\n")
        f.write("# A trailing * marks a Map-typed property, under which any sub-key is valid.\n")
        for name in sorted(names):
            f.write(f"{name}*\n" if names[name] else f"{name}\n")

    maps = sum(1 for v in names.values() if v)
    print(f"\nwrote {OUT.relative_to(ROOT)}: {len(names)} properties, {maps} of them Map-typed")


if __name__ == "__main__":
    main()
